dataset_name: 'zed2i'
meshing:
  eval_rec: True
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 0
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 280
  iters: 10
mapping:
  every_frame: 5
  vis_freq: 50
  vis_inside_freq: 30
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 1000
  iters_first: 1500
  iters: 60
camera_params:
  image_height: 1242
  image_width: 2208
  # HD 2k outside
  fx: 1066.84
  fy: 1067.42
  cx: 1083.98
  cy: 613.52
  png_depth_scale: 1  #for depth image in png format
  crop_edge: 0
